#!/usr/bin/env python3
import gi
from gi.repository import Gio
import subprocess
import time
import os


path = "org.gnome.desktop.wm.preferences"
key = "num-workspaces"
settings = Gio.Settings.new(path)
navpath = os.path.dirname(os.path.abspath(__file__))


def get(cmd):
    try:
        return subprocess.check_output(cmd).decode("utf-8").strip()
    except subprocess.CalledProcessError:
        pass


def get_currws(wspace_data):
    return [l.split()[0] for l in wspace_data.splitlines() if "*" in l][0]


n = 0
maxws1 = None


while True:
    time.sleep(0.5)
    wspace_data = get(["wmctrl", "-d"])
    currws = int(get_currws(wspace_data))
    test = not get(["pgrep", "-f", os.path.join(navpath, "visualspace")])
    if all([wspace_data, test]):
        n_spaces = settings.get_int("num-workspaces")
        if n_spaces - currws <= 1:
            settings.set_int(key, n_spaces + 1)
    else:
        pass
    if n == 10:
        # clean up once per n- seconds (if needed)
        try:
            maxws2 = max([
                int(l.split()[1]) for l in get(
                    ["wmctrl", "-l"]
                ).splitlines()] + [currws])
            settings.set_int(key, maxws2 + 2)
        except AttributeError:
            pass
        else:
            if maxws2 != maxws1:
                settings.set_int(key, maxws2 + 2)
            maxws1 = maxws2
        n = 0
    n = n + 1
