#!/usr/bin/env python3
import subprocess
import os
import gi
from gi.repository import Gio
import shownav_tools as st
import sys
import time


direction = sys.argv[1]
# direction = "next"
navpath = st.navpath
navigator = st.navigator
shownav_busy = st.shownav_busy
shownav_right = st.shownav_right
shownav_left = st.shownav_left
dynamic = st.dynamic


key = st.key
settings = st.settings


def initiate_shownav():
    curr_state = st.get_wsdata()
    add = 0
    # current workspace
    curr = curr_state[0]
    # n-workspaces
    n = curr_state[1]
    # if at the end of the row, add one
    if all([dynamic, direction == "next", curr == n]):
        st.settings.set_int(key, n + 1)
        add = 1
        time.sleep(0.2)
    # set target, 1 is minimum
    target = curr + 1 if direction == "next" else max(curr - 1, 1)
    # run navigator args = targeted workspace, (most recent) n- workspaces
    subprocess.Popen([navigator, str(target), str(n + add)])
    subprocess.Popen(["wmctrl", "-s", str(target - 1)])


def remote_control(direction):
    f = shownav_right if direction == "next" else shownav_left
    open(f, "wt").write("")


if __name__ == "__main__":
    if not any([
        st.get(["pgrep", "-f", "-u", st.user, navigator]),
        os.path.exists(st.shownav_busy),
    ]):
        initiate_shownav()
    else:
        remote_control(direction)
